config/routes.rb
Rails.application.routes.draw do

  get 'graphiques/diagramme'

  get 'graphiques/courbe'

  get 'budgets/edit'

  get 'commentaires/new'

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "dashboard#index"
  get 'dashboard/index'

  resources :ministeres
  resources :plateformes
  resources :programmes
  resources :titres
  resources :actes
  resources :resultat_attenus
  resources :activites
  resources :indicateurs
  resources :budgets
  resources :matrices
  resources :commentaires
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/acte.rb
class Acte < ApplicationRecord
	belongs_to :programme
	has_many :resultat_attenu

  rails_admin do
      label "Action"
      label_plural "Actions"
      list do
          field :nom
          field :description
          field :programme  do
            label "Programme"
          end
          field :created_at
          field :updated_at
      end
      edit do
          field :nom
          field :description, :ck_editor
          field :programme do
            label "Programme"
          end
      end
  end
end

app/models/activite.rb
class Activite < ApplicationRecord
	belongs_to :resultat_attenu
	has_one :indicateur
	has_many :budgets, as: :budgetable
end

app/models/budget.rb
class Budget < ApplicationRecord
	belongs_to :budgetable, polymorphic: true
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
  #belongs_to :user
  belongs_to :matrice
end

app/models/indicateur.rb
class Indicateur < ApplicationRecord
	belongs_to :activite
	has_one :matrice 
end

app/models/matrice.rb
class Matrice < ApplicationRecord
  belongs_to :indicateur
  #belongs_to :activite
  has_many :commentaires
end

app/models/ministere.rb
class Ministere < ApplicationRecord
	has_many :programmes
	has_many :titres
	has_one :plateforme
end

app/models/periode.rb
class Periode < ApplicationRecord
end

app/models/phase.rb
class Phase < ApplicationRecord
	belongs_to :programme
end

app/models/plateforme.rb
class Plateforme < ApplicationRecord
  belongs_to :ministere
  has_many :user

  has_many :thematique_plateformes
  has_many :thematiques, through: :thematique_plateformes
end

app/models/programme.rb
class Programme < ApplicationRecord
  belongs_to :ministere
  has_many :actes
  has_many :budgets, as: :budgetable
  has_many :phases

  has_many :thematique_programmes
  has_many :thematiques, through: :thematique_programmes

  rails_admin do
      label "Programme"
      label_plural "Programmes"
      list do
          field :nom
          field :description
          field :ministere  do
            label "Ministere"
          end
          field :created_at
          field :updated_at
      end
      edit do
          field :nom
          field :description, :ck_editor
          field :ministere do
            label "Ministere"
          end
      end
  end
end

app/models/resultat.rb
class Resultat < ApplicationRecord
  #belongs_to :acte

end

app/models/resultat_attenu.rb
class ResultatAttenu < ApplicationRecord
	belongs_to :acte
	has_many :activites
end

app/models/role.rb
class Role < ApplicationRecord
	has_one :user
end

app/models/thematique.rb
class Thematique < ApplicationRecord
  has_many :thematique_programmes
  has_many :programmes, through: :thematique_programmes

  has_many :thematique_plateformes
  has_many :plateformes, through: :thematique_plateformes
end

app/models/titre.rb
class Titre < ApplicationRecord
  belongs_to :ministere
  #has_and_belongs_to_many :budgets
  has_many :budgets, as: :budgetable
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :plateforme
	belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/matrices_controller.rb
class MatricesController < ApplicationController
  def show
    @matrice = Matrice.all
    @indicateur = Indicateur.find(params[:id])
    @commentaire = Commentaire.all
  end

  # GET /ResultatAttenus/new
  def new
    @matrice = Matrice.new
    @matrice.indicateur_id = params[:indicateur_id]
  end

  # GET /ResultatAttenus/1/edit
  def edit
    @matrice = Matrice.find(params[:id])
  end

  # POST /ResultatAttenus
  # POST /ResultatAttenus.json
  def create

    @matrice = Matrice.new(activite_params)

    respond_to do |format|
      if @matrice.save
        format.html { redirect_to programmes_path, notice: 'Cette matrice a été créé avec succès' }
        format.json { render :show, status: :created, location: @matrice }
      else
        format.html { render :new }
        format.json { render json: @programmes.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ResultatAttenus/1
  # PATCH/PUT /ResultatAttenus/1.json
  def update
    respond_to do |format|
      @matrice = Matrice.find(params[:id])
      if @matrice.update(matrice_params)
        format.html { redirect_to matrix_path(@matrice.id), notice: 'Cette matrice a été mis à jour' }
        format.json { render :show, status: :ok, location: @matrice }
      else
        format.html { render :edit }
        format.json { render json: programmes.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ResultatAttenus/1
  # DELETE /ResultatAttenus/1.json
  def destroy
    @matrice = Matrice.find(params[:id])
    @matrice.destroy
    respond_to do |format|
      format.html { redirect_to programmes_path, notice: 'Cet activité a été supprimé' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matrice
      @matrice = Matrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matrice_params
      params.require(:matrice).permit(:annee, :valeur_initiale, :prevision, :resultat, :ecart, :indicateur_id)
    end

end

app/helpers/actes_helper.rb
module ActesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/matrices_helper.rb
module MatricesHelper
end

app/helpers/titres_helper.rb
module TitresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/matrices/edit.html.erb
            <div class="container-fluid">
                <!-- Start Page Content -->
                <div class="row">
                    
                    <div class="col-lg-12">
                    	<div class="card-header bg-warning center">
                                <h2 class="m-b-0 text-white">Modification</h2>
                    	</div>
                        <div class="card card-outline-info">

                            <%= simple_form_for @matrice do |f| %>
                            <div class="card-header">
                                <h4 class="m-b-0 text-white">Formulaire de modification des informations sur la ligne de matrice (<small>Vérifiez les informations saisies avant de valider</small>)</h4>
                            </div>
                            <div class="card-body m-t-50">
                                    <div class="form-body">
                                        <div class="form-group row">
                                            <%= f.label :annee, "Nom", :class => 'control-label text-right col-md-3' %>
                                            <div class="col-md-9">
                                                <%= f.input :annee, :class => 'form-control', :label => false, :required => true %>
                                                <small class="form-control-feedback"> Modifier l'année de la ligne de matrice </small>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <%= f.label :indicateur_id, "Indicateur", :class => 'control-label text-right col-md-3' %>
                                            <div class="col-md-9">
                                               <%= f.collection_select(:indicateur_id, Indicateur.all, :id, :nom, :class => 'form-control') %>
                                             <small class="form-control-feedback"> Modifiez l'indicateur auquel rattacher la ligne de matrice</small>   
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <%= f.label :valeur_initiale, "Valeur initiale", :class => 'control-label text-right col-md-3' %>
                                            <div class="col-md-9">
                                               <%= f.input :valeur_initiale, :class => 'form-control', :label => false, :required => true,  :rows => "20", style: 'width:100%' %> <small class="form-control-feedback"> Modifier la  valeur initiale </small>  
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <%= f.label :prevision, "Prévision", :class => 'control-label text-right col-md-3' %>
                                            <div class="col-md-9">
                                               <%= f.input :prevision, :class => 'form-control', :label => false, :required => true,  :rows => "20", style: 'width:100%' %> <small class="form-control-feedback"> Modifier la  prévision</small>  
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <%= f.label :resultat, "Réalisation", :class => 'control-label text-right col-md-3' %>
                                            <div class="col-md-9">
                                               <%= f.input :resultat, :class => 'form-control', :label => false, :required => true,  :rows => "20", style: 'width:100%' %> <small class="form-control-feedback"> Modifier la réalisation</small>  
                                            </div>
                                        </div>
                                    
                                    </div>
                                    <div class="form-actions">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="offset-sm-3 col-md-9">
                                                        <%= f.submit "Mise à jour", :class => 'btn btn-themecolor'%>
                                                        <button type="button" class="btn btn-inverse">Annuler</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End PAge Content -->
            </div>

app/views/matrices/index.html.erb
<p id="notice"><%= notice %></p>


                    <div class="row">
                    
                    <!-- /# column -->
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-title">
                                <a href="" class="btn btn-info btn-flat btn-addon"><i class="fa fa-table"></i> Matrice de l'indicateur XXXX</a> 

                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    



                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Année</th>
                                                <th>Résultat de l'an passé</th>
                                                <th>Prévision%</th>
                                                <th>Résultat%</th>
                                                <th>Ecart%</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <tr>    
                                                <th >Dépenses de personnel</th>
                                                <th >1250000000</th>
                                                <th >25000 - <span class="text-danger">25%</span></th>
                                                <th >25000 - <span class="text-danger">35%</th>
                                                <th >25000 - <span class="text-danger">35%</th>
                                                
                                        </tr>
                                          
                                        </tbody>
                                    </table>


                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <!-- /# row -->
               
            

app/views/matrices/show.html.erb
<p id="notice"><%= notice %></p>


                    <div class="row">
                    
                    <!-- /# column -->
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-title">
                                <a href="" class="btn btn-info btn-flat btn-addon"><i class="fa fa-table"></i> Matrice de l'indicateur <%= @indicateur.nom %></a> 

                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    



                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Année</th>
                                                <th>Valeur initiale</th>
                                                <th>Prévision%</th>
                                                <th>Réalisation%</th>
                                                <th>Ecart%</th>
                                                <th>Modifier%</th>
                                                <th>Supprimer%</th>
                                                <th>Commentaires</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <% @matrice.each do |m|%>
                                     	<% if m.indicateur_id == @indicateur.id %>	
                                        <tr>    
                                                <th ><%= m.annee%> </th>
                                                <th ><span class="text-themecolor"><%= m.valeur_initiale%> %</span></th>
                                                <th ><span class="text-themecolor"><%= m.prevision%> %</span></th>
                                                <th ><span class="text-themecolor"><%= m.resultat%> %</span></th>
                                                <th ><span class="text-themecolor"><%= m.prevision - m.resultat %> %</span></th>
                                                <th > <%= link_to 'Modifier', edit_matrix_path(m.id), :class => 'text-danger ', data: {confirm: "Vous êtes sur de vouloir modifier cette ligne de matrice?"}%> <i class="fa fa-edit"></i> </th>
                                                <th >  <%= link_to 'Effacer', matrix_path(m.id), :class => 'text-danger', method: :delete, data: {confirm: "Vous êtes sur de vouloir supprimer cette ligne de matrice?"}%> <i class="fa fa-close"></i></th>
                                                <th > 
                                                	<% @commentaire.each do |c|%>
                                     				<% if c.matrice_id == m.id %>

                                                	<%=c.id %>- <%= c.content %><br/>
                                                	<%end%>
                                                	<%end%>
                                                	<%= link_to 'Ajouter un commentaire', new_commentaire_path(matrice_id: m.id), :class => 'text-danger', data: {confirm: "Vous êtes sur de vouloir ajouter ce commentaire?"}%> <i class="fa fa-plus-square"></i>

                                                	
 												</th>

                                                
                                        </tr>
                                        <%end%> 
                                        <%end%>  
                                        </tbody>
                                    </table>


                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <!-- /# row -->
               
            