config/routes.rb
Rails.application.routes.draw do

  get 'graphiques/diagramme'

  get 'graphiques/courbe'

  get 'budgets/edit'

  get 'commentaires/new'

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "dashboard#index"
  get 'dashboard/index'

  resources :ministeres
  resources :plateformes
  resources :programmes
  resources :titres
  resources :actes
  resources :resultat_attenus
  resources :activites
  resources :indicateurs
  resources :budgets
  resources :matrices
  resources :commentaires
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/acte.rb
class Acte < ApplicationRecord
	belongs_to :programme
	has_many :resultat_attenu

  rails_admin do
      label "Action"
      label_plural "Actions"
      list do
          field :nom
          field :description
          field :programme  do
            label "Programme"
          end
          field :created_at
          field :updated_at
      end
      edit do
          field :nom
          field :description, :ck_editor
          field :programme do
            label "Programme"
          end
      end
  end
end

app/models/activite.rb
class Activite < ApplicationRecord
	belongs_to :resultat_attenu
	has_one :indicateur
	has_many :budgets, as: :budgetable
end

app/models/budget.rb
class Budget < ApplicationRecord
	belongs_to :budgetable, polymorphic: true
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
  #belongs_to :user
  belongs_to :matrice
end

app/models/indicateur.rb
class Indicateur < ApplicationRecord
	belongs_to :activite
	has_one :matrice 
end

app/models/matrice.rb
class Matrice < ApplicationRecord
  belongs_to :indicateur
  #belongs_to :activite
  has_many :commentaires
end

app/models/ministere.rb
class Ministere < ApplicationRecord
	has_many :programmes
	has_many :titres
	has_one :plateforme
end

app/models/periode.rb
class Periode < ApplicationRecord
end

app/models/phase.rb
class Phase < ApplicationRecord
	belongs_to :programme
end

app/models/plateforme.rb
class Plateforme < ApplicationRecord
  belongs_to :ministere
  has_many :user

  has_many :thematique_plateformes
  has_many :thematiques, through: :thematique_plateformes
end

app/models/programme.rb
class Programme < ApplicationRecord
  belongs_to :ministere
  has_many :actes
  has_many :budgets, as: :budgetable
  has_many :phases

  has_many :thematique_programmes
  has_many :thematiques, through: :thematique_programmes

  rails_admin do
      label "Programme"
      label_plural "Programmes"
      list do
          field :nom
          field :description
          field :ministere  do
            label "Ministere"
          end
          field :created_at
          field :updated_at
      end
      edit do
          field :nom
          field :description, :ck_editor
          field :ministere do
            label "Ministere"
          end
      end
  end
end

app/models/resultat.rb
class Resultat < ApplicationRecord
  #belongs_to :acte

end

app/models/role.rb
class Role < ApplicationRecord
	has_one :user
end

app/models/thematique.rb
class Thematique < ApplicationRecord
  has_many :thematique_programmes
  has_many :programmes, through: :thematique_programmes

  has_many :thematique_plateformes
  has_many :plateformes, through: :thematique_plateformes
end

app/models/titre.rb
class Titre < ApplicationRecord
  belongs_to :ministere
  #has_and_belongs_to_many :budgets
  has_many :budgets, as: :budgetable
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :plateforme
	belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/actes_helper.rb
module ActesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/titres_helper.rb
module TitresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_footer.html.erb
<footer class="footer">

</footer>

app/views/shared/_header.html.erb
<!-- header header  -->
        <div class="header">
            <nav class="navbar top-navbar navbar-expand-md navbar-light" style="background-color:  white;">
                <!-- Logo -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="index.html">
                        <!-- Logo icon -->
                        <!-- Logo text -->
                        <h1 style="color:#008000">SAYTU</h1>
                    </a>
                </div>
                <!-- End Logo -->
                <div class="navbar-collapse">
                    <!-- toggle and nav items -->
                    <ul class="navbar-nav mr-auto mt-md-0">
                        
                        <li class="nav-item m-l-10"> <a class="nav-link sidebartoggler hidden-sm-down text-muted  " href="javascript:void(0)"><i class="fa fa-th-large" style="color:#008000"></i></a> </li>

                         
                        
                    </ul>
                    <!-- User profile and search -->
                    <ul class="navbar-nav my-lg-0">
                        <li class="nav-item m-l-10"><%= image_tag asset_path("") %></li>
                        <li class="nav-item m-l-10"><%= image_tag asset_path("logo2.png") %></li>
                        <!-- Search -->
                        <li class="nav-item hidden-sm-down search-box"> <a class="nav-link hidden-sm-down text-muted  " href="javascript:void(0)"><i class="ti-search"></i></a>
                            <form class="app-search">
                                <input type="text" class="form-control" placeholder="Search here"> <a class="srh-btn"><i class="ti-close"></i></a> </form>
                        </li>
                        <!-- 
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted text-muted  " href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-bell"></i>
								<div class="notify"> <span class="heartbit"></span> <span class="point"></span> </div>
							</a>
                            <div class="dropdown-menu dropdown-menu-right mailbox animated zoomIn">
                                <ul>
                                    <li>
                                        <div class="drop-title">Notifications</div>
                                    </li>
                                    <li>
                                        <div class="message-center">
                                           
                                            <a href="#">
                                                <div class="btn btn-danger btn-circle m-r-10"><i class="fa fa-link"></i></div>
                                                <div class="mail-contnet">
                                                    <h5>Deadline données</h5> <span class="mail-desc">NOus avons besoins d'intégrer des données</span> <span class="time">9:30 AM</span>
                                                </div>
                                            </a>

                                        </div>
                                    </li>
                                    <li>
                                        <a class="nav-link text-center" href="javascript:void(0);"> <strong>Consulter toutes les notifications</strong> <i class="fa fa-angle-right"></i> </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                         -->
                
                        <!-- Profile -->
                        
                    </ul>
                </div>
            </nav>
        </div>
        <!-- End header header -->

app/views/shared/_sidebar.html.erb
<!-- Left Sidebar  -->
        <div class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">

                        <li class="nav-devider"></li>
                        <li > <%= link_to root_path do%><i class="fa fa-tachometer"></i><span class="hide-menu">Tableau de bord</span><% end %>
                        </li>

                        <li class="nav-devider"></li>
                        <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-bank"></i><span class="hide-menu">MINISTERE</span></a>
                            <ul aria-expanded="false" class="collapse">
                                <li>
                                <%= link_to "Lister les ministères",ministeres_path %>
                                 </li>
                                <li>
                                <%= link_to "Ajouter un ministère",new_ministere_path %>
                                
                                </li>
                                
                            
                            </ul>
                        </li>
                        <li class="nav-devider"></li>
                        <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-balance-scale"></i><span class="hide-menu">PLATEFORME</span></a>
                            <ul aria-expanded="false" class="collapse">
                                <li>
                                <%= link_to "Lister les plateformes",plateformes_path %>
                                 </li>
                                <li>
                                <%= link_to "Ajouter une plateforme",new_plateforme_path %>
                                
                                </li>
                                

                            </ul>
                        </li>
                        <li class="nav-devider"></li>
                        <li> <a class="has-arrow" href="#" aria-expanded="false"><i class="fa fa-table"></i><span class="hide-menu"> Programmes</span></a>
                                    <ul aria-expanded="false" class="collapse">
                                        <li>
                                            <%= link_to "Tableau des programmes",programmes_path %>
                                        </li>
                                        <li>
                                            <%= link_to "Ajouter un programme",new_programme_path %>
                                        </li>
                                        <li>
                                        
                                    </ul>
                        </li>
                        <li class="nav-devider"></li>
                        <li> <a class="has-arrow" href="#" aria-expanded="false"><i class="fa fa-folder"></i><span class="hide-menu"> Titres</span></a>
                                    <ul aria-expanded="false" class="collapse">
                                        <li>
                                            <%= link_to "Tableau des titres",titres_path %>
                                        </li>
                                        <li>
                                            <%= link_to "Ajouter un titre",new_titre_path%>
                                        </li>
                                        
                                    </ul>
                        </li>
                        
                        <li class="nav-devider"></li>
                        <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-bar-chart"></i><span class="hide-menu">GRAPHIQUES</span></a>
                            <ul aria-expanded="false" class="collapse">
                                <li>
                                            <%= link_to "Programmes",graphiques_diagramme_path %>
                                </li>
                                <li>
                                            <%= link_to "Titres",graphiques_courbe_path %>
                                </li>
                                
                            </ul>
                        </li>
                        
                        
                        <li class="nav-devider"></li>
                        <ul class="dropdown-user">
                                   © 2019 All rights reserved.  
                        </ul>


                    
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </div>
        <!-- End Left Sidebar  -->

app/views/shared/messagerie.html.erb
<li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-envelope"></i><span class="hide-menu">MESSAGERIE</span></a>
                            <ul aria-expanded="false" class="collapse">
                                <li><a href="email-compose.html">Nouveau message</a></li>
                                <!--<li><a href="email-read.html">Read</a></li> -->
                                <li><a href="email-inbox.html">Boite de reception</a></li>
                            </ul>
                        </li>